version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sdajharkhand-tourism-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ansh
      MONGO_INITDB_ROOT_PASSWORD: ansh123
      MONGO_INITDB_DATABASE: sih-gyan-setu
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data_v5:/data/db
    networks:
      - backend-network

volumes:
  mongodb_data_v5:
    driver: local

networks:
  backend-network:
    driver: bridge
